In [154]:
# import torchtext.vocab

# glove = torchtext.vocab.Vectors('toastynews.vec', cache='./vectors/')
# #glove2 = torchtext.vocab.Vectors('cc.zh.300.vec', cache='./vectors/')
# #glove3 = torchtext.vocab.Vectors('model.txt', cache='./vectors/')

## Read Text Corpus

In [1]:
import docx
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import pickle

In [75]:
doc = docx.Document('诗.docx')

In [76]:
data = ""
all_sentences = []
for para in doc.paragraphs:
    text = para.text.replace('    ', '，').replace(' ', '，').replace('，，', '，').replace('，，', '，').replace('！', '。').replace('，', '。')
    text = text.replace('。', '\n')
    
    if text[-1] == '\n':
        text = text[:-1]
    
    text = text.split('\n')
    all_sentences += text
    data = '\n'.join(all_sentences)

print(data)

冬日暖阳真好
北晖园中寻宝
景映双儿姿
徐晖入湖添娇
闲捣
闲捣
辛苦一袋天椒
红梅敖雪正值冬
几朵艳梅竞相红
一夜霜风绛满地
入土为垢掩姿容
归
今夕明朝又几时
魂何在
不染入徐晖
山
前路迢兮道且弯
人需慢
身在景中延
卿卿细语兮
慰之吾心
卿卿佳才兮
倾之吾心
卿卿俊姿兮
痴之吾心
子以惜之兮
唯诺长留
子以挽之兮
唯卿可留
子以念之兮
唯笺弥留
遥问子卿兮
佳期如斯
对镜梳妆容颜净
笑看风云
处处桃花剩
半盏残茶昏渡日
寄予青墨书孤影
醉卧窗前西风冷
清梦幽幽
又见君临境
偎与子卿双鬓白
西风已老情依竟
梨花羞白西堤
柳如丝
摇曳乌蓬如画进诗词
折子戏
泪相思
泣离时
梦遇良人如昔伴卿归
折身隐入廊中
月无踪
寂夜还逢烟雨醉灯笼
捻花弄
枝枝痛
又伤风
离别红尘幽梦与谁同
繁星月小朦胧
夜无风
翠柳青青垂面碧波重
繁星转
小月映
喜争逢
轻折柳枝缠绕醉其中
微风细细吟秋
静悠悠
踏入墨香书屋把闲求
一笺纸
一平仄
一丝羞
撒落相思几点待君收
西风夜半入窗门
清酌飘香满玉盆
盼得与君欢对饮
一书一笔一丝魂
椒浆欲染香腮艳
半阕诗词泪半痕
莫问蛾眉因谁画
痴心只待夜来昏
夜半西风入重门
庭前桂花映玉盆
盼得与君月下饮
一唱一和吟花魂
琼浆欲染香艳腮
半阕诗词伴泪痕
莫问蛾眉因谁画
天涯望断夜已昏
夜半西风入闺门
手提桂花映玉盆
并肩与卿月下饮
一人一首吟花魂
琼浆羞红伊人腮
半阕诗词沾泪痕
我为伊人画蛾眉
执手天涯赴黄昏
烟雨蒙蒙染小庄
堤边杨柳抵河塘
白墙青瓦陈时雨
深巷朱桥李家郞
山雾雾
水茫茫
孤舟莫怕行程长
相逢不恨身先许
顾首还欣相思常
昨夜挑灯绣新装
临晨对镜贴花黄
浅脂粉淡画容妆
莫笑衣裳颜色少
心藏丽华有芳香
红颜可否立身傍
殷殷相约
负于吾心
纵吾来兮
子宁不在兮
殷殷相盼
唯念汝心
纵汝无嗣音
吾依常在兮
愠兮怨兮
偏生执念沉痴兮
寒兮冷兮
轻于柳絮重霜兮
十里桃林花中凤
满地嫣红
朵朵春风送
瓣瓣生姿招尔宠
桃花情劫芳心动
独入桃林花易弄
镜中人儿
镜外佳人梦
俯首折枝心事重
三生眷念谁人懂
蓝衣袖
金丝纽
锦衣还鲜红颜旧
残风卷
桃花散
一夜斜雨
几书离眷
叹
叹
叹
山盟有
锦书瘦
欲将相思轻弹奏
东楼转
西窗盼
鸿鸟归来
木依枝半
怨
怨
怨
晓秋月照云轻
夜吹笙
只首望辰星点点如萤
风拂面
似呢语
细喃聆
又见卢家郞以曲书情
夜雨西

In [77]:
len(all_sentences)

725

In [78]:
max_length = 9

max_length

9

In [79]:
data = list(set(data))
len(data)

997

In [80]:
data

['完',
 '前',
 '静',
 '鲜',
 '施',
 '赤',
 '浪',
 '取',
 '悠',
 '恸',
 '节',
 '音',
 '先',
 '电',
 '绣',
 '穹',
 '吹',
 '冷',
 '宁',
 '钗',
 '东',
 '亭',
 '炽',
 '蹂',
 '窈',
 '声',
 '别',
 '倾',
 '纸',
 '明',
 '心',
 '竹',
 '忙',
 '求',
 '衬',
 '吟',
 '临',
 '且',
 '稽',
 '符',
 '嚣',
 '孑',
 '残',
 '傍',
 '早',
 '骨',
 '醇',
 '昙',
 '装',
 '萝',
 '含',
 '竟',
 '赐',
 '已',
 '予',
 '凭',
 '庭',
 '呢',
 '化',
 '牵',
 '旧',
 '添',
 '互',
 '朵',
 '纽',
 '陪',
 '叶',
 '好',
 '袋',
 '昏',
 '带',
 '惹',
 '悲',
 '月',
 '曳',
 '斯',
 '笙',
 '北',
 '梵',
 '呈',
 '贤',
 '常',
 '词',
 '蒙',
 '桑',
 '掩',
 '须',
 '脑',
 '帘',
 '忘',
 '章',
 '沿',
 '蜿',
 '诺',
 '缷',
 '终',
 '注',
 '鸿',
 '捃',
 '侣',
 '公',
 '而',
 '一',
 '轮',
 '笼',
 '娉',
 '瓢',
 '溃',
 '翻',
 '埋',
 '焰',
 '君',
 '婷',
 '淅',
 '往',
 '酒',
 '烟',
 '面',
 '愁',
 '慧',
 '迷',
 '却',
 '丽',
 '沉',
 '投',
 '寂',
 '堪',
 '驳',
 '萼',
 '衣',
 '谷',
 '苍',
 '梅',
 '履',
 '开',
 '季',
 '落',
 '斑',
 '欣',
 '肩',
 '谁',
 '欢',
 '拈',
 '蕾',
 '恻',
 '真',
 '烦',
 '盛',
 '捣',
 '蕴',
 '归',
 '此',
 '邀',
 '与',
 '年',
 '恐',
 '琴',
 '约',
 '平',
 '屋',
 '剩',
 '奈',
 '妙',
 '葬',
 '像',
 '说',
 '廊'

In [81]:
vocab_itos = {}
vocab_stoi = {}

for i, w in enumerate(data):
        vocab_itos[i] = w
        vocab_stoi[w] = i

In [82]:
vocab_itos

{0: '完',
 1: '前',
 2: '静',
 3: '鲜',
 4: '施',
 5: '赤',
 6: '浪',
 7: '取',
 8: '悠',
 9: '恸',
 10: '节',
 11: '音',
 12: '先',
 13: '电',
 14: '绣',
 15: '穹',
 16: '吹',
 17: '冷',
 18: '宁',
 19: '钗',
 20: '东',
 21: '亭',
 22: '炽',
 23: '蹂',
 24: '窈',
 25: '声',
 26: '别',
 27: '倾',
 28: '纸',
 29: '明',
 30: '心',
 31: '竹',
 32: '忙',
 33: '求',
 34: '衬',
 35: '吟',
 36: '临',
 37: '且',
 38: '稽',
 39: '符',
 40: '嚣',
 41: '孑',
 42: '残',
 43: '傍',
 44: '早',
 45: '骨',
 46: '醇',
 47: '昙',
 48: '装',
 49: '萝',
 50: '含',
 51: '竟',
 52: '赐',
 53: '已',
 54: '予',
 55: '凭',
 56: '庭',
 57: '呢',
 58: '化',
 59: '牵',
 60: '旧',
 61: '添',
 62: '互',
 63: '朵',
 64: '纽',
 65: '陪',
 66: '叶',
 67: '好',
 68: '袋',
 69: '昏',
 70: '带',
 71: '惹',
 72: '悲',
 73: '月',
 74: '曳',
 75: '斯',
 76: '笙',
 77: '北',
 78: '梵',
 79: '呈',
 80: '贤',
 81: '常',
 82: '词',
 83: '蒙',
 84: '桑',
 85: '掩',
 86: '须',
 87: '脑',
 88: '帘',
 89: '忘',
 90: '章',
 91: '沿',
 92: '蜿',
 93: '诺',
 94: '缷',
 95: '终',
 96: '注',
 97: '鸿',
 98: '捃',
 99: '侣',
 100: '公',

## Skip-gram Train Data Extraction

In [205]:
all_int_sentences = np.zeros((725, 9))
X = np.zeros((725 * 10, 2))
y = np.zeros((725 * 10, 1))
k = 9

for i, s in enumerate(tqdm(all_sentences)):
    int_s = [vocab_stoi[i] for i in list(s)]
    
    if len(int_s) != 1:
        context = np.random.randint(0, len(int_s))
        pos_target = np.random.randint(0, len(int_s))
        
        while context == pos_target:
            pos_target = np.random.randint(0, len(int_s))
        else:
            X[i * 10] = np.array([int_s[context], int_s[pos_target]]).reshape(1, 2)
            y[i * 10] = 1
            
        for n in range(k):
            neg_target = np.random.randint(0, 997)
            X[n + i * 10 + 1] = np.array([int_s[context], neg_target]).reshape(1, 2)
        
    while len(int_s) != 9:
        int_s.append(0)
            
    all_int_sentences[i] = np.array(int_s).reshape(1, 9) 

100%|██████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 9440.82it/s]


## Word Embeddings Training

In [208]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from functools import partial

batch_size = 50
buffer_size = 1000

train_data = tf.data.Dataset.from_tensor_slices((X, y))
train_data = train_data.cache().shuffle(buffer_size).batch(batch_size).repeat()

print(X.shape)
print(train_data)

embedding_dim = 16
vocab_size = 997

model = Sequential([
    Embedding(vocab_size, embedding_dim),
    LSTM(64, return_sequences=False),
    Dense(16, activation='tanh'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001, 
                                             beta_1=0.999, beta_2=0.999, epsilon=10**-8),
                                             loss='binary_crossentropy',
                                             metrics=['accuracy'])
model.summary()

(7250, 2)
<RepeatDataset shapes: ((None, 2), (None, 1)), types: (tf.float64, tf.float64)>
Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_25 (Embedding)     (None, None, 16)          15952     
_________________________________________________________________
lstm_20 (LSTM)               (None, 64)                20736     
_________________________________________________________________
dense_51 (Dense)             (None, 16)                1040      
_________________________________________________________________
dense_52 (Dense)             (None, 1)                 17        
Total params: 37,745
Trainable params: 37,745
Non-trainable params: 0
_________________________________________________________________


In [85]:
train_step = len(X) // batch_size

In [86]:
model.fit(x=train_data, 
          epochs=100,
          steps_per_epoch=train_step,
          verbose=2)

Train for 145 steps
Epoch 1/100
145/145 - 1s - loss: 0.4264 - accuracy: 0.9023
Epoch 2/100
145/145 - 0s - loss: 0.3334 - accuracy: 0.9052
Epoch 3/100
145/145 - 0s - loss: 0.3300 - accuracy: 0.9052
Epoch 4/100
145/145 - 0s - loss: 0.2958 - accuracy: 0.9052
Epoch 5/100
145/145 - 0s - loss: 0.2838 - accuracy: 0.9052
Epoch 6/100
145/145 - 0s - loss: 0.2633 - accuracy: 0.9052
Epoch 7/100
145/145 - 0s - loss: 0.2407 - accuracy: 0.9047
Epoch 8/100
145/145 - 0s - loss: 0.2348 - accuracy: 0.9048
Epoch 9/100
145/145 - 0s - loss: 0.2347 - accuracy: 0.9079
Epoch 10/100
145/145 - 0s - loss: 0.2259 - accuracy: 0.9065
Epoch 11/100
145/145 - 0s - loss: 0.2227 - accuracy: 0.9068
Epoch 12/100
145/145 - 0s - loss: 0.2236 - accuracy: 0.9061
Epoch 13/100
145/145 - 0s - loss: 0.2225 - accuracy: 0.9051
Epoch 14/100
145/145 - 0s - loss: 0.2174 - accuracy: 0.9037
Epoch 15/100
145/145 - 0s - loss: 0.2127 - accuracy: 0.9043
Epoch 16/100
145/145 - 0s - loss: 0.2129 - accuracy: 0.9090
Epoch 17/100
145/145 - 0s - l

In [87]:
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) # shape: (vocab_size, embedding_dim)

(997, 16)


## Save word matrix and dicts

In [88]:
import pickle
import numpy as np

for names, files in zip(['all_sentences', 'all_int_sentences', 'vocab_stoi', 'vocab_itos'], 
                        [all_sentences, all_int_sentences, vocab_stoi, vocab_itos]):
    f = open('{0}.pkl'.format(names), "wb")
    pickle.dump(files, f)
    f.close()
np.save('word_matrix.npy', weights)

In [2]:
word_matrix = np.load('word_matrix.npy')

In [3]:
f = open('vocab_stoi.pkl', 'rb')
stoi = pickle.load(f)
f.close()

In [4]:
f = open('vocab_itos.pkl', 'rb')
itos = pickle.load(f)
f.close()

In [5]:
f = open('all_int_sentences.pkl', 'rb')
sentences = pickle.load(f)
f.close()

In [6]:
f = open('all_sentences.pkl', 'rb')
str_sentences = pickle.load(f)
f.close()

In [7]:
# np.save('X_ohe.npy', X)
# np.save('y_ohe.npy', y)
X = np.load('X_ohe.npy')
y = np.load('y_ohe.npy')

In [6]:
len(stoi)

997

In [7]:
stoi['\n']

501

In [8]:
itos[501]

'\n'

In [9]:
stoi

{'完': 0,
 '前': 1,
 '静': 2,
 '鲜': 3,
 '施': 4,
 '赤': 5,
 '浪': 6,
 '取': 7,
 '悠': 8,
 '恸': 9,
 '节': 10,
 '音': 11,
 '先': 12,
 '电': 13,
 '绣': 14,
 '穹': 15,
 '吹': 16,
 '冷': 17,
 '宁': 18,
 '钗': 19,
 '东': 20,
 '亭': 21,
 '炽': 22,
 '蹂': 23,
 '窈': 24,
 '声': 25,
 '别': 26,
 '倾': 27,
 '纸': 28,
 '明': 29,
 '心': 30,
 '竹': 31,
 '忙': 32,
 '求': 33,
 '衬': 34,
 '吟': 35,
 '临': 36,
 '且': 37,
 '稽': 38,
 '符': 39,
 '嚣': 40,
 '孑': 41,
 '残': 42,
 '傍': 43,
 '早': 44,
 '骨': 45,
 '醇': 46,
 '昙': 47,
 '装': 48,
 '萝': 49,
 '含': 50,
 '竟': 51,
 '赐': 52,
 '已': 53,
 '予': 54,
 '凭': 55,
 '庭': 56,
 '呢': 57,
 '化': 58,
 '牵': 59,
 '旧': 60,
 '添': 61,
 '互': 62,
 '朵': 63,
 '纽': 64,
 '陪': 65,
 '叶': 66,
 '好': 67,
 '袋': 68,
 '昏': 69,
 '带': 70,
 '惹': 71,
 '悲': 72,
 '月': 73,
 '曳': 74,
 '斯': 75,
 '笙': 76,
 '北': 77,
 '梵': 78,
 '呈': 79,
 '贤': 80,
 '常': 81,
 '词': 82,
 '蒙': 83,
 '桑': 84,
 '掩': 85,
 '须': 86,
 '脑': 87,
 '帘': 88,
 '忘': 89,
 '章': 90,
 '沿': 91,
 '蜿': 92,
 '诺': 93,
 '缷': 94,
 '终': 95,
 '注': 96,
 '鸿': 97,
 '捃': 98,
 '侣': 99,
 '公': 100,

In [10]:
sentences

array([[450., 388., 438., ...,   0.,   0.,   0.],
       [ 77., 538., 259., ...,   0.,   0.,   0.],
       [807., 667., 957., ...,   0.,   0.,   0.],
       ...,
       [118., 377., 387., ...,   0.,   0.,   0.],
       [892., 951., 987., ..., 163.,   0.,   0.],
       [887., 111., 307., ..., 557.,   0.,   0.]])

## Train Data Extraction

In [104]:
# '\n' is not in sentences, we could generate stop signal manually.
print(len(set(sentences.ravel())))
print(len(stoi))

996
997


In [163]:
# from tqdm import tqdm
# train_data = np.ones((sentences.shape[0], sentences.shape[1], word_matrix.shape[1])) * 997
# labels = np.ones(train_data.shape) * 997
# stop_signal = stoi['\n']

# for i, s in enumerate(tqdm(sentences)):
    
#     s = s.astype(int)
#     for tx in range(train_data.shape[1]):
#         train_data[i, tx, :] = new_word_matrix[s[tx], :]
    
#     if 997 in s:
#         index = np.where(s == 997)[0][0]
#         train_data[i, index, :] = new_word_matrix[stop_signal, :]
#         labels[i, :-1, :] = train_data[i, 1:, :]
#         labels[i, -1, :] = new_word_matrix[997, :]
#     else:
#         labels[i, :-1, :] = train_data[i, 1:, :]
#         labels[i, -1, :] = new_word_matrix[stop_signal, :]

100%|█████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 51837.14it/s]


## Train data with one hot encoding

In [6]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse=False)
encoder.fit(pd.DataFrame(data=range(997)))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [13]:
stop_signal = stoi['\n']
stop_signal

501

In [14]:
sentences.shape

(725, 9)

In [138]:
X = np.zeros((sentences.shape[0], sentences.shape[1], 997))
y = np.zeros(X.shape)
stop_signal = stoi['\n']

for i, s in enumerate(tqdm(sentences)):
    
    
    if 0 in s:
        index = np.where(s == 0)[0][0]
        X[i, :index, :] = encoder.transform(s[:index].astype(int).reshape(-1, 1))
        y[i, :-1, :] = X[i, 1:, :]
        y[i, index - 1, :] = encoder.transform(np.array([[stop_signal]]))
    else:
        X[i, :, :] = encoder.transform(s.astype(int).reshape(-1, 1))
        y[i, :-1, :] = X[i, 1:, :]
        y[i, -1, :] = encoder.transform(np.array([[stop_signal]]))

100%|██████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 2106.89it/s]


In [148]:
sentences[685]

array([413., 356., 154., 570., 459., 903.,   8.,   8.,   0.])

In [149]:
for i in X[685, :, :]:
    print(np.where(i == 1))

(array([413], dtype=int64),)
(array([356], dtype=int64),)
(array([154], dtype=int64),)
(array([570], dtype=int64),)
(array([459], dtype=int64),)
(array([903], dtype=int64),)
(array([8], dtype=int64),)
(array([8], dtype=int64),)
(array([], dtype=int64),)


In [150]:
for i in y[685, :, :]:
    print(np.where(i == 1))

(array([356], dtype=int64),)
(array([154], dtype=int64),)
(array([570], dtype=int64),)
(array([459], dtype=int64),)
(array([903], dtype=int64),)
(array([8], dtype=int64),)
(array([8], dtype=int64),)
(array([501], dtype=int64),)
(array([], dtype=int64),)


In [155]:
X.shape

(725, 9, 997)

In [156]:
y.shape

(725, 9, 997)

In [157]:
X.shape[-2:]

(9, 997)

In [158]:
word_matrix

array([[ 1.2627708 ,  1.1184896 ,  0.65846604, ..., -0.2740781 ,
         1.2805173 , -0.7691841 ],
       [-0.16701148, -0.04800417,  0.10223731, ...,  0.3736675 ,
        -0.09602794,  0.15016608],
       [ 0.45625833,  0.47412494,  0.28183857, ..., -0.07690182,
         0.4851833 , -0.3467303 ],
       ...,
       [ 0.5957525 ,  0.56621236,  0.27712682, ..., -0.08323597,
         0.5743058 , -0.47823912],
       [-0.23219244, -0.19996862, -0.09762999, ...,  0.10853168,
        -0.29874095,  0.14187166],
       [ 0.46292078,  0.43443447,  0.294577  , ..., -0.135622  ,
         0.3966606 , -0.3200521 ]], dtype=float32)

## Model building

In [8]:
BATCH_SIZE = 1
BUFFER_SIZE = 725

train_data = tf.data.Dataset.from_tensor_slices((sentences, y))
train_data = train_data.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True).repeat()

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Dropout
from tensorflow.keras.initializers import Constant

model = tf.keras.models.Sequential([
    Embedding(word_matrix.shape[0], word_matrix.shape[1], 
              batch_input_shape=[BATCH_SIZE, None], # None is compatible with any sizes
              embeddings_initializer=Constant(word_matrix),
              trainable=False),
    LSTM(256, return_sequences=True, stateful=True), # stateful requires to state batch size
    Dense(1024, activation='tanh'),
    Dense(word_matrix.shape[0], activation='tanh'),
    Dense(word_matrix.shape[0], activation='softmax'),
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001, 
                                                 beta_1=0.99, beta_2=0.999, epsilon=10**-8),
                                                 loss='categorical_crossentropy')

model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_7 (Embedding)      (1, None, 16)             15952     
_________________________________________________________________
lstm_7 (LSTM)                (1, None, 256)            279552    
_________________________________________________________________
dense_21 (Dense)             (1, None, 1024)           263168    
_________________________________________________________________
dense_22 (Dense)             (1, None, 997)            1021925   
_________________________________________________________________
dense_23 (Dense)             (1, None, 997)            995006    
Total params: 2,575,603
Trainable params: 2,559,651
Non-trainable params: 15,952
_________________________________________________________________


In [8]:
import os 

checkpoint_dir = 'training_checkpoints/'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True,
    save_freq=5)

In [39]:
model.fit(x=train_data, 
          epochs=50,
          steps_per_epoch=len(sentences) // BATCH_SIZE,
          callbacks=[checkpoint_callback],
          verbose=2)

Train for 725 steps
Epoch 1/50
725/725 - 26s - loss: 3.3683
Epoch 2/50
725/725 - 27s - loss: 3.1033
Epoch 3/50
725/725 - 27s - loss: 3.0312
Epoch 4/50
725/725 - 28s - loss: 2.9844
Epoch 5/50
725/725 - 29s - loss: 2.9151
Epoch 6/50
725/725 - 28s - loss: 2.8556
Epoch 7/50
725/725 - 27s - loss: 2.8002
Epoch 8/50
725/725 - 27s - loss: 2.7203
Epoch 9/50
725/725 - 137s - loss: 2.6738
Epoch 10/50
725/725 - 28s - loss: 2.6129
Epoch 11/50
725/725 - 28s - loss: 2.5288
Epoch 12/50
725/725 - 29s - loss: 2.4438
Epoch 13/50
725/725 - 29s - loss: 2.3391
Epoch 14/50
725/725 - 28s - loss: 2.2919
Epoch 15/50
725/725 - 28s - loss: 2.2598
Epoch 16/50
725/725 - 28s - loss: 2.2340
Epoch 17/50
725/725 - 29s - loss: 2.1193
Epoch 18/50
725/725 - 28s - loss: 2.0625
Epoch 19/50
725/725 - 29s - loss: 2.0374
Epoch 20/50
725/725 - 28s - loss: 1.9995
Epoch 21/50
725/725 - 29s - loss: 1.9873
Epoch 22/50
725/725 - 28s - loss: 1.8507
Epoch 23/50
725/725 - 28s - loss: 1.7697
Epoch 24/50
725/725 - 28s - loss: 1.7332
Epoc

In [9]:
checkpoint_dir = 'training_checkpoints/'
latest = tf.train.latest_checkpoint(checkpoint_dir)
latest

'training_checkpoints/ckpt_50'

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Dropout
from tensorflow.keras.initializers import Constant

model2 = tf.keras.models.Sequential([
    Embedding(word_matrix.shape[0], word_matrix.shape[1], batch_input_shape=[1, None],
              embeddings_initializer=Constant(word_matrix),
              trainable=False),
    LSTM(256, return_sequences=True, stateful=True),
    Dense(1024, activation='tanh'),
    Dense(word_matrix.shape[0], activation='tanh'),
    Dense(word_matrix.shape[0], activation='softmax'),
])

model2.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (1, None, 16)             15952     
_________________________________________________________________
lstm (LSTM)                  (1, None, 256)            279552    
_________________________________________________________________
dense (Dense)                (1, None, 1024)           263168    
_________________________________________________________________
dense_1 (Dense)              (1, None, 997)            1021925   
_________________________________________________________________
dense_2 (Dense)              (1, None, 997)            995006    
Total params: 2,575,603
Trainable params: 2,559,651
Non-trainable params: 15,952
_________________________________________________________________


In [11]:
model2.load_weights(latest)

In [12]:
def sample(preds, vocab_size, itos):
    idx = np.random.choice(np.arange(vocab_size), 1, True, preds)[0]
    
    return idx

In [25]:
model2.predict(np.zeros((13, 10))).shape

(13, 10, 997)

In [27]:
## It is like [batch_size, [:9]] as first input and It is like [batch_size, [1:10]] as the second input

In [18]:
model2.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (1, None, 16)             15952     
_________________________________________________________________
lstm (LSTM)                  (1, None, 256)            279552    
_________________________________________________________________
dense (Dense)                (1, None, 1024)           263168    
_________________________________________________________________
dense_1 (Dense)              (1, None, 997)            1021925   
_________________________________________________________________
dense_2 (Dense)              (1, None, 997)            995006    
Total params: 2,575,603
Trainable params: 2,559,651
Non-trainable params: 15,952
_________________________________________________________________


In [22]:
model2.input_shape

(1, None)

In [54]:
def generate_text_xjh(model, num_generate, num_per_row):
    # Evaluation step (generating text using the learned model)

    # Converting our start string to numbers (vectorizing)
    input_eval = np.zeros([1])
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = ''
    
    row = 0
    word = 0
    predicted_id = None
    for i in range(num_generate):
        
        if i != 0 and i % num_per_row == 0:
            text_generated += '\n'
            row += 1
            word = 0
            
        pause_cond = ((row == 0)and(word == 6)) or ((row == 2)and(word == 3 or word == 6))
        
        if pause_cond:
            text_generated += ','
            
        predictions = model2.predict(input_eval)
        # remove the batch dimension
        predictions =  tf.squeeze(predictions, [0, 1]).numpy()

        # using a categorical distribution to predict the character returned by the model
        predicted_id = sample(predictions, 997, itos)
        
        while predicted_id == stoi['\n']:
            predicted_id = sample(predictions, 997, itos)
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated += itos[predicted_id]
        word += 1
        
    return (text_generated)

In [45]:
def generate_text(model, num_generate, num_per_row):
    # Evaluation step (generating text using the learned model)

    # Converting our start string to numbers (vectorizing)
    input_eval = np.zeros([1])
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = ''
    
    count = 0
    predicted_id = None
    
    for i in range(num_generate):
        
        if i!= 0 and i % num_per_row == 0:
            text_generated += '\n'
        
        predictions = model2.predict(input_eval)
        # remove the batch dimension
        predictions =  tf.squeeze(predictions, [0, 1]).numpy()

        # using a categorical distribution to predict the character returned by the model
        predicted_id = sample(predictions, 997, itos)
        
        while predicted_id == stoi['\n']:
            predicted_id = sample(predictions, 997, itos)
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated += itos[predicted_id]
        
    return (text_generated)

In [46]:
def generate_text_by_starter(model, num_generate, starter):
    # Evaluation step (generating text using the learned model)

    # Converting our start string to numbers (vectorizing)
    input_eval = np.array([stoi[starter]])
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = starter
    
    count = 0
    predicted_id = None
    
    for i in range(num_generate):
        
        if (i+1) % 5 == 0:
            text_generated += '\n'
        
        predictions = model2.predict(input_eval)
        # remove the batch dimension
        predictions =  tf.squeeze(predictions, [0, 1]).numpy()

        # using a categorical distribution to predict the character returned by the model
        predicted_id = sample(predictions, 997, itos)
        
        while predicted_id == stoi['\n']:
            predicted_id = sample(predictions, 997, itos)
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated += itos[predicted_id]
        
    return (text_generated)

In [40]:
print(generate_text_by_starter(model2, 19, '君'))

君雨烟雨来
老断兮半颜
为波恻遗娜
牵情喜沾怜


In [44]:
print(generate_text(model2, 20))


伏去生执手
天涯赴黄如
鲜妍雪夜来
风友伊意浅


In [45]:
print(generate_text(model2, 20))


阴来来帘起
将娆送月雨
绵常痕小香
飘飘恨渡余


In [46]:
print(generate_text(model2, 20))


伏涎春柳送
丝雾雨绵寒
花弄地妓量
殷还冢朦同


In [55]:
for i in range(2):
    print('第{0}首柳絮诗集生成器: '.format(i+1))
    print(generate_text_xjh(model2, 36, 9))
    print('\n')

第1首柳絮诗集生成器: 
春来堤边浅瞳,春抵伴
西棂雨廊与花欢手曳
绒摘叶,词怜临,妆手头
乌中如还千姿百痕可


第2首柳絮诗集生成器: 
春颜叶君君心,花两还
还结同同嚣叶映断难
难终怎,尽两亡,亡成结
同心蕴恩魄烟边道伴




In [9]:
def cosine_similarity(u, v):
    """
    Cosine similarity reflects the degree of similarity between u and v
        
    Arguments:
        u -- a word vector of shape (n,)          
        v -- a word vector of shape (n,)

    Returns:
        cosine_similarity -- the cosine similarity between u and v defined by the formula above.
    """
    
    distance = 0.0

    dot = np.dot(u, v)
    norm_u = np.sqrt(np.sum(u**2))
    norm_v = np.sqrt(np.sum(v**2))
    cosine_similarity = dot/(norm_u * norm_v)
    
    return cosine_similarity

In [15]:
w = word_mat

In [16]:
cosine_similarity(word_matrix[stoi['君'], :], word_matrix[stoi['卿'], :])

0.5897598

In [17]:
cosine_similarity(w[stoi['君'], :], w[stoi['柳'], :])

0.374642

In [18]:
cosine_similarity(w[stoi['山'], :], w[stoi['树'], :])

-0.32440615

In [19]:
cosine_similarity(w[stoi['凄'], :], w[stoi['凉'], :])

0.98948145

In [20]:
cosine_similarity(w[stoi['凄'], :], w[stoi['暗'], :])

-0.4717849

In [21]:
cosine_similarity(w[stoi['凄'], :], w[stoi['爱'], :])

0.63953996