In [385]:
# import torchtext.vocab

# glove = torchtext.vocab.Vectors('toastynews.vec', cache='./vectors/')
# #glove2 = torchtext.vocab.Vectors('cc.zh.300.vec', cache='./vectors/')
# #glove3 = torchtext.vocab.Vectors('model.txt', cache='./vectors/')

## Read Text Corpus

In [464]:
import docx
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import pickle

In [465]:
doc = docx.Document('诗.docx')

In [466]:
data = ""
all_sentences = []
for para in doc.paragraphs:
    text = para.text.replace('    ', '，').replace(' ', '，').replace('，，', '，').replace('，，', '，').replace('！', '。').replace('，', '。')
    text = text.replace('。', '\n')
    
    if text[-1] == '\n':
        text = text[:-1]
    
    text = text.split('\n')
    all_sentences += text
    data = '\n'.join(all_sentences)

print(data)

冬日暖阳真好
北晖园中寻宝
景映双儿姿
徐晖入湖添娇
闲捣
闲捣
辛苦一袋天椒
红梅敖雪正值冬
几朵艳梅竞相红
一夜霜风绛满地
入土为垢掩姿容
归
今夕明朝又几时
魂何在
不染入徐晖
山
前路迢兮道且弯
人需慢
身在景中延
卿卿细语兮
慰之吾心
卿卿佳才兮
倾之吾心
卿卿俊姿兮
痴之吾心
子以惜之兮
唯诺长留
子以挽之兮
唯卿可留
子以念之兮
唯笺弥留
遥问子卿兮
佳期如斯
对镜梳妆容颜净
笑看风云
处处桃花剩
半盏残茶昏渡日
寄予青墨书孤影
醉卧窗前西风冷
清梦幽幽
又见君临境
偎与子卿双鬓白
西风已老情依竟
梨花羞白西堤
柳如丝
摇曳乌蓬如画进诗词
折子戏
泪相思
泣离时
梦遇良人如昔伴卿归
折身隐入廊中
月无踪
寂夜还逢烟雨醉灯笼
捻花弄
枝枝痛
又伤风
离别红尘幽梦与谁同
繁星月小朦胧
夜无风
翠柳青青垂面碧波重
繁星转
小月映
喜争逢
轻折柳枝缠绕醉其中
微风细细吟秋
静悠悠
踏入墨香书屋把闲求
一笺纸
一平仄
一丝羞
撒落相思几点待君收
西风夜半入窗门
清酌飘香满玉盆
盼得与君欢对饮
一书一笔一丝魂
椒浆欲染香腮艳
半阕诗词泪半痕
莫问蛾眉因谁画
痴心只待夜来昏
夜半西风入重门
庭前桂花映玉盆
盼得与君月下饮
一唱一和吟花魂
琼浆欲染香艳腮
半阕诗词伴泪痕
莫问蛾眉因谁画
天涯望断夜已昏
夜半西风入闺门
手提桂花映玉盆
并肩与卿月下饮
一人一首吟花魂
琼浆羞红伊人腮
半阕诗词沾泪痕
我为伊人画蛾眉
执手天涯赴黄昏
烟雨蒙蒙染小庄
堤边杨柳抵河塘
白墙青瓦陈时雨
深巷朱桥李家郞
山雾雾
水茫茫
孤舟莫怕行程长
相逢不恨身先许
顾首还欣相思常
昨夜挑灯绣新装
临晨对镜贴花黄
浅脂粉淡画容妆
莫笑衣裳颜色少
心藏丽华有芳香
红颜可否立身傍
殷殷相约
负于吾心
纵吾来兮
子宁不在兮
殷殷相盼
唯念汝心
纵汝无嗣音
吾依常在兮
愠兮怨兮
偏生执念沉痴兮
寒兮冷兮
轻于柳絮重霜兮
十里桃林花中凤
满地嫣红
朵朵春风送
瓣瓣生姿招尔宠
桃花情劫芳心动
独入桃林花易弄
镜中人儿
镜外佳人梦
俯首折枝心事重
三生眷念谁人懂
蓝衣袖
金丝纽
锦衣还鲜红颜旧
残风卷
桃花散
一夜斜雨
几书离眷
叹
叹
叹
山盟有
锦书瘦
欲将相思轻弹奏
东楼转
西窗盼
鸿鸟归来
木依枝半
怨
怨
怨
晓秋月照云轻
夜吹笙
只首望辰星点点如萤
风拂面
似呢语
细喃聆
又见卢家郞以曲书情
夜雨西

In [467]:
len(all_sentences)

725

In [468]:
max_length = 9

max_length

9

In [469]:
data = list(set(data))
len(data)

997

In [470]:
data

['茫',
 '两',
 '髻',
 '拿',
 '燕',
 '薄',
 '牙',
 '腑',
 '浅',
 '婷',
 '叙',
 '抵',
 '新',
 '陌',
 '隔',
 '花',
 '顾',
 '后',
 '料',
 '发',
 '嫦',
 '陪',
 '陷',
 '息',
 '剩',
 '萝',
 '孤',
 '路',
 '依',
 '蛾',
 '破',
 '醴',
 '滂',
 '青',
 '嚣',
 '芳',
 '凉',
 '季',
 '寂',
 '骑',
 '魁',
 '棒',
 '良',
 '里',
 '艳',
 '思',
 '姸',
 '饰',
 '之',
 '灵',
 '今',
 '郡',
 '棂',
 '贤',
 '侧',
 '葬',
 '菊',
 '土',
 '恩',
 '简',
 '分',
 '松',
 '悲',
 '笺',
 '章',
 '摘',
 '掩',
 '妍',
 '纷',
 '斗',
 '哪',
 '衬',
 '跚',
 '嘻',
 '祛',
 '隐',
 '纳',
 '萍',
 '吁',
 '蔻',
 '罩',
 '尖',
 '阅',
 '苍',
 '髅',
 '怅',
 '大',
 '爱',
 '曲',
 '过',
 '坻',
 '清',
 '轮',
 '袋',
 '落',
 '残',
 '城',
 '贱',
 '而',
 '送',
 '矮',
 '偶',
 '寞',
 '冬',
 '断',
 '我',
 '寰',
 '首',
 '换',
 '临',
 '流',
 '牵',
 '映',
 '四',
 '朵',
 '沁',
 '君',
 '读',
 '折',
 '夜',
 '逢',
 '欢',
 '岸',
 '赤',
 '偏',
 '车',
 '栖',
 '似',
 '自',
 '鳞',
 '昏',
 '肠',
 '昔',
 '果',
 '至',
 '本',
 '封',
 '北',
 '蝶',
 '留',
 '生',
 '浊',
 '染',
 '轻',
 '施',
 '慧',
 '注',
 '戏',
 '瓣',
 '掉',
 '调',
 '值',
 '挽',
 '悄',
 '逝',
 '廊',
 '和',
 '魄',
 '慰',
 '岁',
 '携',
 '阕',
 '天',
 '跋',
 '看',
 '外',
 '醇'

In [473]:
vocab_itos = {}
vocab_stoi = {}

for i, w in enumerate(data):
        vocab_itos[i] = w
        vocab_stoi[w] = i
        
vocab_itos[i+1] = 'pad'
vocab_stoi['pad'] = i+1

In [474]:
vocab_itos

{0: '茫',
 1: '两',
 2: '髻',
 3: '拿',
 4: '燕',
 5: '薄',
 6: '牙',
 7: '腑',
 8: '浅',
 9: '婷',
 10: '叙',
 11: '抵',
 12: '新',
 13: '陌',
 14: '隔',
 15: '花',
 16: '顾',
 17: '后',
 18: '料',
 19: '发',
 20: '嫦',
 21: '陪',
 22: '陷',
 23: '息',
 24: '剩',
 25: '萝',
 26: '孤',
 27: '路',
 28: '依',
 29: '蛾',
 30: '破',
 31: '醴',
 32: '滂',
 33: '青',
 34: '嚣',
 35: '芳',
 36: '凉',
 37: '季',
 38: '寂',
 39: '骑',
 40: '魁',
 41: '棒',
 42: '良',
 43: '里',
 44: '艳',
 45: '思',
 46: '姸',
 47: '饰',
 48: '之',
 49: '灵',
 50: '今',
 51: '郡',
 52: '棂',
 53: '贤',
 54: '侧',
 55: '葬',
 56: '菊',
 57: '土',
 58: '恩',
 59: '简',
 60: '分',
 61: '松',
 62: '悲',
 63: '笺',
 64: '章',
 65: '摘',
 66: '掩',
 67: '妍',
 68: '纷',
 69: '斗',
 70: '哪',
 71: '衬',
 72: '跚',
 73: '嘻',
 74: '祛',
 75: '隐',
 76: '纳',
 77: '萍',
 78: '吁',
 79: '蔻',
 80: '罩',
 81: '尖',
 82: '阅',
 83: '苍',
 84: '髅',
 85: '怅',
 86: '大',
 87: '爱',
 88: '曲',
 89: '过',
 90: '坻',
 91: '清',
 92: '轮',
 93: '袋',
 94: '落',
 95: '残',
 96: '城',
 97: '贱',
 98: '而',
 99: '送',
 100: '矮',

## Skip-gram Train Data Extraction

In [475]:
all_int_sentences = np.zeros((725, 9))
X = np.zeros((725 * 10, 2))
y = np.zeros((725 * 10, 1))
k = 9

for i, s in enumerate(tqdm(all_sentences)):
    int_s = [vocab_stoi[i] for i in list(s)]
    
    if len(int_s) != 1:
        context = np.random.randint(0, len(int_s))
        pos_target = np.random.randint(0, len(int_s))
        
        while context == pos_target:
            pos_target = np.random.randint(0, len(int_s))
        else:
            X[i * 10] = np.array([int_s[context], int_s[pos_target]]).reshape(1, 2)
            y[i * 10] = 1
            
        for n in range(k):
            neg_target = np.random.randint(0, 997)
            X[n + i * 10 + 1] = np.array([int_s[context], neg_target]).reshape(1, 2)
        
    while len(int_s) != 9:
        int_s.append(997)
            
    all_int_sentences[i] = np.array(int_s).reshape(1, 9) 

100%|█████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 15298.13it/s]


## Word Embeddings Training

In [477]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from functools import partial

batch_size = 50
buffer_size = 1000

train_data = tf.data.Dataset.from_tensor_slices((X, y))
train_data = train_data.cache().shuffle(buffer_size).batch(batch_size).repeat()

print(X.shape)
print(train_data)

embedding_dim = 16
vocab_size = 998

model = Sequential([
    Embedding(vocab_size, embedding_dim),
    LSTM(64, return_sequences=False),
    Dense(16, activation='tanh'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001, 
                                             beta_1=0.999, beta_2=0.999, epsilon=10**-8),
                                             loss='binary_crossentropy',
                                             metrics=['accuracy'])
model.summary()

(7250, 2)
<RepeatDataset shapes: ((None, 2), (None, 1)), types: (tf.float64, tf.float64)>
Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_21 (Embedding)     (None, None, 16)          15968     
_________________________________________________________________
lstm_13 (LSTM)               (None, 64)                20736     
_________________________________________________________________
dense_27 (Dense)             (None, 16)                1040      
_________________________________________________________________
dense_28 (Dense)             (None, 1)                 17        
Total params: 37,761
Trainable params: 37,761
Non-trainable params: 0
_________________________________________________________________


In [478]:
train_step = len(X) // batch_size

In [479]:
model.fit(x=train_data, 
          epochs=100,
          steps_per_epoch=train_step,
          verbose=2)

Epoch 1/100
145/145 - 2s - loss: 0.4227 - accuracy: 0.9029
Epoch 2/100
145/145 - 0s - loss: 0.3257 - accuracy: 0.9052
Epoch 3/100
145/145 - 0s - loss: 0.3268 - accuracy: 0.9052
Epoch 4/100
145/145 - 0s - loss: 0.2869 - accuracy: 0.9052
Epoch 5/100
145/145 - 0s - loss: 0.2732 - accuracy: 0.9052
Epoch 6/100
145/145 - 0s - loss: 0.2480 - accuracy: 0.9052
Epoch 7/100
145/145 - 0s - loss: 0.2312 - accuracy: 0.9017
Epoch 8/100
145/145 - 0s - loss: 0.2372 - accuracy: 0.8968
Epoch 9/100
145/145 - 0s - loss: 0.2261 - accuracy: 0.9059
Epoch 10/100
145/145 - 0s - loss: 0.2196 - accuracy: 0.9083
Epoch 11/100
145/145 - 0s - loss: 0.2225 - accuracy: 0.9068
Epoch 12/100
145/145 - 0s - loss: 0.2234 - accuracy: 0.9079
Epoch 13/100
145/145 - 0s - loss: 0.2195 - accuracy: 0.9084
Epoch 14/100
145/145 - 0s - loss: 0.2131 - accuracy: 0.9074
Epoch 15/100
145/145 - 0s - loss: 0.2109 - accuracy: 0.9083
Epoch 16/100
145/145 - 0s - loss: 0.2107 - accuracy: 0.9092
Epoch 17/100
145/145 - 0s - loss: 0.2067 - accura

In [480]:
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) # shape: (vocab_size, embedding_dim)

(998, 16)


In [481]:
model.variables[0].shape

TensorShape([998, 16])

In [482]:
emb = tf.keras.layers.Embedding(
            input_dim=10, output_dim=50,  # [enc_n_vocab, emb_dim]
            embeddings_initializer=tf.initializers.RandomNormal(0, 0.1))
emb.variables

[]

## Save word matrix and dicts

In [483]:
import pickle
import numpy as np

for names, files in zip(['all_sentences', 'all_int_sentences', 'vocab_stoi', 'vocab_itos'], 
                        [all_sentences, all_int_sentences, vocab_stoi, vocab_itos]):
    f = open('{0}.pkl'.format(names), "wb")
    pickle.dump(files, f)
    f.close()
np.save('word_matrix.npy', weights)

In [484]:
word_matrix = np.load('word_matrix.npy')

In [485]:
f = open('vocab_stoi.pkl', 'rb')
stoi = pickle.load(f)
f.close()

In [486]:
f = open('vocab_itos.pkl', 'rb')
itos = pickle.load(f)
f.close()

In [487]:
f = open('all_int_sentences.pkl', 'rb')
sentences = pickle.load(f)
f.close()

In [488]:
f = open('all_sentences.pkl', 'rb')
str_sentences = pickle.load(f)
f.close()

In [489]:
# np.save('X_ohe.npy', X)
# np.save('y_ohe.npy', y)

X = np.load('X_ohe.npy')
y = np.load('y_ohe.npy')

In [490]:
len(stoi)

998

In [491]:
stoi['\n']

992

In [492]:
itos[501]

'常'

In [493]:
stoi

{'茫': 0,
 '两': 1,
 '髻': 2,
 '拿': 3,
 '燕': 4,
 '薄': 5,
 '牙': 6,
 '腑': 7,
 '浅': 8,
 '婷': 9,
 '叙': 10,
 '抵': 11,
 '新': 12,
 '陌': 13,
 '隔': 14,
 '花': 15,
 '顾': 16,
 '后': 17,
 '料': 18,
 '发': 19,
 '嫦': 20,
 '陪': 21,
 '陷': 22,
 '息': 23,
 '剩': 24,
 '萝': 25,
 '孤': 26,
 '路': 27,
 '依': 28,
 '蛾': 29,
 '破': 30,
 '醴': 31,
 '滂': 32,
 '青': 33,
 '嚣': 34,
 '芳': 35,
 '凉': 36,
 '季': 37,
 '寂': 38,
 '骑': 39,
 '魁': 40,
 '棒': 41,
 '良': 42,
 '里': 43,
 '艳': 44,
 '思': 45,
 '姸': 46,
 '饰': 47,
 '之': 48,
 '灵': 49,
 '今': 50,
 '郡': 51,
 '棂': 52,
 '贤': 53,
 '侧': 54,
 '葬': 55,
 '菊': 56,
 '土': 57,
 '恩': 58,
 '简': 59,
 '分': 60,
 '松': 61,
 '悲': 62,
 '笺': 63,
 '章': 64,
 '摘': 65,
 '掩': 66,
 '妍': 67,
 '纷': 68,
 '斗': 69,
 '哪': 70,
 '衬': 71,
 '跚': 72,
 '嘻': 73,
 '祛': 74,
 '隐': 75,
 '纳': 76,
 '萍': 77,
 '吁': 78,
 '蔻': 79,
 '罩': 80,
 '尖': 81,
 '阅': 82,
 '苍': 83,
 '髅': 84,
 '怅': 85,
 '大': 86,
 '爱': 87,
 '曲': 88,
 '过': 89,
 '坻': 90,
 '清': 91,
 '轮': 92,
 '袋': 93,
 '落': 94,
 '残': 95,
 '城': 96,
 '贱': 97,
 '而': 98,
 '送': 99,
 '矮': 100,

In [494]:
sentences

array([[103., 977., 846., ..., 997., 997., 997.],
       [137., 592., 260., ..., 997., 997., 997.],
       [679., 112., 341., ..., 997., 997., 997.],
       ...,
       [248., 186., 192., ..., 997., 997., 997.],
       [340., 886., 703., ...,  55., 997., 997.],
       [371., 116., 275., ..., 423., 997., 997.]])

## Train Data Extraction

In [496]:
# '\n' is not in sentences, we could generate stop signal manually.
print(len(set(sentences.ravel())))
print(len(stoi))

997
998


In [497]:
# from tqdm import tqdm
# train_data = np.ones((sentences.shape[0], sentences.shape[1], word_matrix.shape[1])) * 997
# labels = np.ones(train_data.shape) * 997
# stop_signal = stoi['\n']

# for i, s in enumerate(tqdm(sentences)):
    
#     s = s.astype(int)
#     for tx in range(train_data.shape[1]):
#         train_data[i, tx, :] = new_word_matrix[s[tx], :]
    
#     if 997 in s:
#         index = np.where(s == 997)[0][0]
#         train_data[i, index, :] = new_word_matrix[stop_signal, :]
#         labels[i, :-1, :] = train_data[i, 1:, :]
#         labels[i, -1, :] = new_word_matrix[997, :]
#     else:
#         labels[i, :-1, :] = train_data[i, 1:, :]
#         labels[i, -1, :] = new_word_matrix[stop_signal, :]

## Train data with one hot encoding

In [518]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse=False)
encoder.fit(pd.DataFrame(data=range(998)))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [519]:
stop_signal = stoi['\n']
stop_signal

992

In [520]:
sentences.shape

(725, 9)

In [521]:
sentences[287, :]

array([531., 996., 358.,  72., 134., 997., 997., 997., 997.])

In [522]:
str_sentences[287]

'步履蹒跚至'

In [523]:
int_s

[371, 116, 275, 831, 341, 126, 423, 997, 997]

In [557]:
for i,s in enumerate(sentences):
    if 997 not in s:
        print(i, s)

45 [733. 842. 403. 187. 221. 325. 598. 655. 736.]
49 [831. 388.  42. 379. 221. 132. 228. 715. 236.]
52 [ 38. 119. 840. 120. 716. 202. 839. 956. 575.]
56 [641. 784. 988. 180. 959. 831. 329. 303. 697.]
59 [171. 608.  33.  33. 991. 285. 967. 326. 304.]
63 [143. 118. 608. 507. 321. 555. 839. 647. 825.]
66 [522. 622. 291. 695. 772. 879. 332. 760. 505.]
70 [758.  94. 703.  45. 451. 425. 371. 116. 632.]
154 [869. 107. 984. 929. 816. 425. 425. 221. 203.]
158 [794. 510. 807. 394. 558. 169.  88. 772. 731.]
231 [516. 608. 249. 907. 260. 474. 329. 116. 120.]
235 [654. 984. 537. 759. 217. 217. 451. 281. 697.]
238 [460. 122.  13. 797. 486. 701. 860. 116. 393.]
242 [714. 719.  14. 180. 665. 336. 623. 655. 736.]


In [545]:
X = np.zeros((sentences.shape[0], sentences.shape[1], 998))
y = np.zeros(X.shape)
stop_signal = stoi['\n']

for i, s in enumerate(tqdm(sentences)):
    
#     if 997 in s:
#         index = np.where(s==997)[0][0]
#         X[i, :index, :] = encoder.transform(s[:index].astype(int).reshape(-1, 1))
#         y[i, :-1, :] = X[i, 1:, :]
#         y[i, index-1, :] = encoder.transform(np.array([[stop_signal]]))
#     else:
#         X[i, :, :] = encoder.transform(s.astype(int).reshape(-1, 1))
#         y[i, :-1, :] = X[i, 1:, :]
#         y[i, -1, :] = encoder.transform(np.array([[stop_signal]]))
    if 997 in s:
        index = np.where(s==997)[0][0]
        X[i, :, :] = encoder.transform(s[:].astype(int).reshape(-1, 1))
        y[i, :-1, :] = X[i, 1:, :]
        y[i, index-1, :] = encoder.transform(np.array([[stop_signal]]))
        y[i, -1, :] = encoder.transform(np.array([[997]]))
    else:
        X[i, :, :] = encoder.transform(s.astype(int).reshape(-1, 1))
        y[i, :-1, :] = X[i, 1:, :]
        y[i, -1, :] = encoder.transform(np.array([[stop_signal]]))

100%|██████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 1173.99it/s]


In [558]:
sentences[45]

array([733., 842., 403., 187., 221., 325., 598., 655., 736.])

In [559]:
for i in X[45, :, :]:
    print(np.where(i == 1))

(array([733], dtype=int64),)
(array([842], dtype=int64),)
(array([403], dtype=int64),)
(array([187], dtype=int64),)
(array([221], dtype=int64),)
(array([325], dtype=int64),)
(array([598], dtype=int64),)
(array([655], dtype=int64),)
(array([736], dtype=int64),)


In [560]:
for i in y[45, :, :]:
    print(np.where(i == 1))

(array([842], dtype=int64),)
(array([403], dtype=int64),)
(array([187], dtype=int64),)
(array([221], dtype=int64),)
(array([325], dtype=int64),)
(array([598], dtype=int64),)
(array([655], dtype=int64),)
(array([736], dtype=int64),)
(array([992], dtype=int64),)


In [561]:
X.shape

(725, 9, 998)

In [562]:
y.shape

(725, 9, 998)

In [563]:
X.shape[-2:]

(9, 998)

In [564]:
word_matrix

array([[-0.0976193 ,  1.0228646 ,  1.2878643 , ...,  0.57988584,
        -1.0455521 ,  0.53171045],
       [-0.25879127, -0.05388558, -0.1675447 , ..., -0.10299023,
         0.06470545,  0.3077201 ],
       [ 0.22950885,  0.41783503,  0.34585056, ...,  0.35370302,
        -0.32047802,  0.28441325],
       ...,
       [ 0.07957481,  0.02104129,  0.01279772, ...,  0.162561  ,
         0.09474035,  0.32638687],
       [ 0.21755111,  0.59176016,  0.5675481 , ...,  0.56387055,
        -0.5684769 ,  0.20254952],
       [ 0.02657953, -0.00817863, -0.04185339, ...,  0.04668992,
         0.04076267, -0.0327975 ]], dtype=float32)

## Model building

In [565]:
BATCH_SIZE = 1
BUFFER_SIZE = 725

train_data = tf.data.Dataset.from_tensor_slices((sentences, y))
train_data = train_data.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True).repeat()

In [566]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Dropout
from tensorflow.keras.initializers import Constant

model = tf.keras.models.Sequential([
    Embedding(word_matrix.shape[0], word_matrix.shape[1], 
              batch_input_shape=[BATCH_SIZE, None], # None is compatible with any sizes
              embeddings_initializer=Constant(word_matrix),
              trainable=False),
    LSTM(256, return_sequences=True, stateful=True), # stateful requires to state batch size
    Dense(1024, activation='tanh'),
    Dense(word_matrix.shape[0], activation='tanh'),
    Dense(word_matrix.shape[0], activation='softmax'),
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001, 
                                                 beta_1=0.99, beta_2=0.999, epsilon=10**-8),
                                                 loss='categorical_crossentropy')

model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_23 (Embedding)     (1, None, 16)             15968     
_________________________________________________________________
lstm_14 (LSTM)               (1, None, 256)            279552    
_________________________________________________________________
dense_29 (Dense)             (1, None, 1024)           263168    
_________________________________________________________________
dense_30 (Dense)             (1, None, 998)            1022950   
_________________________________________________________________
dense_31 (Dense)             (1, None, 998)            997002    
Total params: 2,578,640
Trainable params: 2,562,672
Non-trainable params: 15,968
_________________________________________________________________


In [567]:
import os 

checkpoint_dir = 'training_checkpoints/'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True,
    save_freq=5)

In [568]:
model.fit(x=train_data, 
          epochs=50,
          steps_per_epoch=len(sentences) // BATCH_SIZE,
          callbacks=[checkpoint_callback],
          verbose=2)

Epoch 1/50
725/725 - 34s - loss: 4.6881
Epoch 2/50
725/725 - 32s - loss: 3.9005
Epoch 3/50
725/725 - 32s - loss: 3.4648
Epoch 4/50
725/725 - 36s - loss: 3.4161
Epoch 5/50
725/725 - 37s - loss: 3.1822
Epoch 6/50
725/725 - 34s - loss: 3.0944
Epoch 7/50
725/725 - 36s - loss: 3.0344
Epoch 8/50
725/725 - 35s - loss: 2.9007
Epoch 9/50
725/725 - 32s - loss: 2.8529
Epoch 10/50
725/725 - 32s - loss: 2.7982
Epoch 11/50
725/725 - 34s - loss: 2.6968
Epoch 12/50
725/725 - 33s - loss: 2.6295
Epoch 13/50
725/725 - 33s - loss: 2.5482
Epoch 14/50
725/725 - 33s - loss: 2.4860
Epoch 15/50
725/725 - 32s - loss: 2.3858
Epoch 16/50
725/725 - 32s - loss: 2.3405
Epoch 17/50
725/725 - 34s - loss: 2.2564
Epoch 18/50
725/725 - 33s - loss: 2.1385
Epoch 19/50
725/725 - 35s - loss: 2.0682
Epoch 20/50
725/725 - 34s - loss: 1.9955
Epoch 21/50
725/725 - 34s - loss: 1.8823
Epoch 22/50
725/725 - 32s - loss: 1.8206
Epoch 23/50
725/725 - 32s - loss: 1.7503
Epoch 24/50
725/725 - 34s - loss: 1.6587
Epoch 25/50
725/725 - 34s

In [569]:
checkpoint_dir = 'training_checkpoints/'
latest = tf.train.latest_checkpoint(checkpoint_dir)
latest

'training_checkpoints/ckpt_50'

In [570]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Dropout
from tensorflow.keras.initializers import Constant

model2 = tf.keras.models.Sequential([
    Embedding(word_matrix.shape[0], word_matrix.shape[1], batch_input_shape=[1, None],
              embeddings_initializer=Constant(word_matrix),
              trainable=False),
    LSTM(256, return_sequences=True, stateful=True),
    Dense(1024, activation='tanh'),
    Dense(word_matrix.shape[0], activation='tanh'),
    Dense(word_matrix.shape[0], activation='softmax'),
])

model2.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_24 (Embedding)     (1, None, 16)             15968     
_________________________________________________________________
lstm_15 (LSTM)               (1, None, 256)            279552    
_________________________________________________________________
dense_32 (Dense)             (1, None, 1024)           263168    
_________________________________________________________________
dense_33 (Dense)             (1, None, 998)            1022950   
_________________________________________________________________
dense_34 (Dense)             (1, None, 998)            997002    
Total params: 2,578,640
Trainable params: 2,562,672
Non-trainable params: 15,968
_________________________________________________________________


In [571]:
model2.load_weights(latest)

In [572]:
def sample(preds, vocab_size, itos):
    idx = np.random.choice(np.arange(vocab_size), 1, True, preds)[0]
    
    return idx

## The model could predict with any shape of input (m, time_step), because the time_step is None in the model when building.

In [573]:
model2.predict(np.zeros((13, 7))).shape

InvalidArgumentError:    Specified a list with shape [1,16] from a tensor with shape [13,16]
	 [[{{node TensorArrayUnstack/TensorListFromTensor}}]]
	 [[sequential_15/lstm_15/PartitionedCall]] [Op:__inference_predict_function_1435373]

Function call stack:
predict_function -> predict_function -> predict_function


In [ ]:
model2.predict(np.zeros((13, 9))).shape

In [574]:
input_eval = np.zeros([1])
input_eval = tf.expand_dims(input_eval, 0)

In [575]:
input_eval.shape

TensorShape([1, 1])

In [576]:
np.array([[1]]).shape

(1, 1)

In [577]:
sample(model2.predict(input_eval), 997, itos)

ValueError: 'p' must be 1-dimensional

In [578]:
model2.predict(np.array([[1]]))

array([[[3.61273857e-03, 3.90094044e-07, 6.11288664e-09, 4.72215426e-11,
         2.79306134e-10, 4.85707278e-05, 3.62929409e-10, 3.82302315e-11,
         2.24456298e-09, 3.75726721e-08, 2.29613647e-06, 4.66038637e-06,
         4.97046828e-14, 3.41766199e-10, 6.18833873e-10, 1.49459127e-04,
         1.65925565e-10, 5.76279345e-12, 3.04681798e-05, 3.34738859e-09,
         2.89038304e-09, 1.65744016e-10, 4.06847516e-12, 1.83465710e-14,
         5.69280004e-04, 6.56288955e-12, 2.28871731e-11, 3.67594566e-07,
         5.56413643e-02, 1.15871013e-09, 5.54434753e-13, 4.10147177e-12,
         8.01446583e-13, 1.59395153e-09, 3.10897939e-11, 1.56662794e-10,
         1.65073435e-12, 5.77695793e-08, 1.69664158e-10, 1.60958771e-05,
         3.16639182e-09, 1.06981562e-10, 1.75413606e-09, 3.95512600e-09,
         1.42590204e-06, 2.50970703e-11, 3.09165512e-06, 6.29854716e-14,
         5.91315086e-09, 4.92853480e-10, 1.41338200e-11, 3.69415470e-10,
         9.10863829e-10, 1.26380573e-10, 3.28530918

In [579]:
## It is like [batch_size, [:9]] as first input and It is like [batch_size, [1:10]] as the second input

In [580]:
model2.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_24 (Embedding)     (1, None, 16)             15968     
_________________________________________________________________
lstm_15 (LSTM)               (1, None, 256)            279552    
_________________________________________________________________
dense_32 (Dense)             (1, None, 1024)           263168    
_________________________________________________________________
dense_33 (Dense)             (1, None, 998)            1022950   
_________________________________________________________________
dense_34 (Dense)             (1, None, 998)            997002    
Total params: 2,578,640
Trainable params: 2,562,672
Non-trainable params: 15,968
_________________________________________________________________


In [581]:
model2.input_shape

(1, None)

In [606]:
def generate_text_xjh(model, num_generate, num_per_row):
    # Evaluation step (generating text using the learned model)

    # Converting our start string to numbers (vectorizing)
    input_eval = np.zeros([1])
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = ''
    
    row = 0
    word = 0
    predicted_id = None
    for i in range(num_generate):
        
        if i != 0 and i % num_per_row == 0:
            text_generated += '\n'
            row += 1
            word = 0
            
        pause_cond = ((row == 0)and(word == 6)) or ((row == 2)and(word == 3 or word == 6))
        
        if pause_cond:
            text_generated += ','
            
        predictions = model2.predict(input_eval)
        # remove the batch dimension
        predictions =  tf.squeeze(predictions, [0, 1]).numpy()

        # using a categorical distribution to predict the character returned by the model
        predicted_id = sample(predictions, 998, itos)
        
        while predicted_id == stoi['\n']:
            predicted_id = sample(predictions, 998, itos)
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated += itos[predicted_id]
        word += 1
        
    return (text_generated)

In [602]:
import tensorflow as tf
import numpy as np

input_eval = np.zeros([1])
input_eval = tf.expand_dims(input_eval, 0)

In [603]:
input_eval

<tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[0.]])>

In [604]:
 tf.expand_dims([2], 0)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]])>

In [608]:
def generate_text(model, num_generate, num_per_row):
    # Evaluation step (generating text using the learned model)

    # Converting our start string to numbers (vectorizing)
    input_eval = np.zeros([1])
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = ''
    
    count = 0
    predicted_id = None
    
    for i in range(num_generate):
        
        if i!= 0 and i % num_per_row == 0:
            text_generated += '\n'
        
        predictions = model2.predict(input_eval)
        # remove the batch dimension
        predictions =  tf.squeeze(predictions, [0, 1]).numpy()

        # using a categorical distribution to predict the character returned by the model
        predicted_id = sample(predictions, 998, itos)
        
        while predicted_id == stoi['\n'] or predicted_id == stoi['pad']:
            predicted_id = sample(predictions, 998, itos)
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated += itos[predicted_id]
        
    return (text_generated)

In [612]:
def generate_text_by_starter(model, num_generate, starter):
    # Evaluation step (generating text using the learned model)

    # Converting our start string to numbers (vectorizing)
    input_eval = np.array([stoi[starter]])
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = starter
    
    count = 0
    predicted_id = None
    
    for i in range(num_generate):
        
        if (i+1) % 5 == 0:
            text_generated += '\n'
        
        predictions = model2.predict(input_eval)
        # remove the batch dimension
        predictions =  tf.squeeze(predictions, [0, 1]).numpy()

        # using a categorical distribution to predict the character returned by the model
        predicted_id = sample(predictions, 998, itos)
        
        while predicted_id == stoi['\n'] or predicted_id == stoi['pad']:
            predicted_id = sample(predictions, 998, itos)
        # We pass the predicted character as the next input to the model
        # along with the previous hidden state
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated += itos[predicted_id]
        
    return (text_generated)

In [613]:
print(generate_text_by_starter(model2, 19, '君'))

君心飞将半
逢对镜梅竞
相卿如斯痛
君心悦起语


In [614]:
print(generate_text(model2, 20, 5))

际影绯重重
重重如好在
风入相思念
如虹雨新地


In [616]:
print(generate_text(model2, 20, 5))

分笑看老语
翠波凭眉郞
之三成框艳
王送茫茫絮


In [618]:
print(generate_text(model2, 20, 5))

际影行腮完
地褐丝垂声
一团蒲一起
俗处处处处


In [619]:
for i in range(2):
    print('第{0}首柳絮诗集生成器: '.format(i+1))
    print(generate_text_xjh(model2, 36, 9))
    print('\n')

第1首柳絮诗集生成器: 
茫庄佛眼涟涟,侣家郞
花徐好成成葬絮如半
对镜梳,妆地轻,风笑雨
丝丝如即妍友友涟诗


第2首柳絮诗集生成器: 
茫茫际影一穷,虹情缠
堪声公子涟来之心老
冬情俏,虹缕家,寒卷送
风丝半丝丝落絮絮盼




In [9]:
def cosine_similarity(u, v):
    """
    Cosine similarity reflects the degree of similarity between u and v
        
    Arguments:
        u -- a word vector of shape (n,)          
        v -- a word vector of shape (n,)

    Returns:
        cosine_similarity -- the cosine similarity between u and v defined by the formula above.
    """
    
    distance = 0.0

    dot = np.dot(u, v)
    norm_u = np.sqrt(np.sum(u**2))
    norm_v = np.sqrt(np.sum(v**2))
    cosine_similarity = dot/(norm_u * norm_v)
    
    return cosine_similarity

In [15]:
w = word_mat

In [16]:
cosine_similarity(word_matrix[stoi['君'], :], word_matrix[stoi['卿'], :])

0.5897598

In [17]:
cosine_similarity(w[stoi['君'], :], w[stoi['柳'], :])

0.374642

In [18]:
cosine_similarity(w[stoi['山'], :], w[stoi['树'], :])

-0.32440615

In [19]:
cosine_similarity(w[stoi['凄'], :], w[stoi['凉'], :])

0.98948145

In [20]:
cosine_similarity(w[stoi['凄'], :], w[stoi['暗'], :])

-0.4717849

In [21]:
cosine_similarity(w[stoi['凄'], :], w[stoi['爱'], :])

0.63953996